### PR TITLE
Price Prediction Staging

### LINKED ISSUE #20: Price predictions
We need to be able to predict the electricity price from the Elexon API.

SLIMJaB already implement a solution we can reuse.

### PR DESCRIPTION
**Pull request by fjebaker**
Most of the price prediction code has now been converted and seems to spit out prediction when given forecast data okay, but there are a few problems.

At the basic level, we don't know what the models really are, and some of the data (the DERSY data) goes entirely unused (I think it is training data?).

We also have
- #22 

I am reluctant to commit the models, as they are many megabytes in size, and I don't want to pollute the git history. I am wondering how best to deploy these, perhaps upload them as release objects which get fetched over the web when first run / during docker building.

I will open an issue relating to this in a moment.

If  `model.p` and `scaling.p` are put into the `src/pricing/` directory, then the following script (used for testing and to later add the unit tests) will work:
```py
import mariadb
import pandas

import src.pricing.pricing as pricing

conn = mariadb.connect(
    user="aimlac",
    password="aimlac",
    host="127.0.0.1",
    port=3306,
    database="llanwrytd"
)

cursor = conn.cursor()

def get_all_from(table):
    cursor.execute(f"SELECT * FROM {table}")
    result = cursor.fetchall()

    cursor.execute(f"SHOW COLUMNS FROM {table}")
    column_names = [i[0] for i in cursor.fetchall()]

    df = pandas.DataFrame(result, columns=column_names)
    return df

b0620 = get_all_from("elexonB0620")
b1620 = get_all_from("elexonB1620")

forecast = pricing.prepare_data_frame(b0620, b1620)

output = pricing.get_price_forecast(forecast)
print(output)

conn.close()
```

I'm opening this PR because it goes a significant way to getting the pricing prediction working, and invites discussion before we continue with development. As mention, we need to address:

- how are models being shipped?
- where will the models be stored?
- do we try to update the models (maybe for the future)?

### CODE REVIEW

**Comment by fjebaker** [comment]
@samhennessey requesting you take a look at this also, as building models is what (if I remember right) you would be investigating further for the extensions. The above decisions will most likely affect how you will approach that 👍

**Comment by samhennessey** [comment]
> @samhennessey requesting you take a look at this also, as building models is what (if I remember right) you would be investigating further for the extensions. The above decisions will most likely affect how you will approach that 👍

@fjebaker Will do, my aim this week is to hopefully have a plan on how the models are going to be developed. I spent some time pre-processing the data you sent me last week and I'm concerned that we don't have enough data to train and test the models. I also need to determine what exactly the target variables that we want to be predicting are and in turn determine the number of models that need to be created and trained.

I've got a plot of the times from each table in the database to ensure we have the same timeframe for all, this is what I have: 
image

**Comment by fjebaker** [comment]
@samhennessey sounds good! You should be able to use the 'live' database on the google VM with more complete and recent data -- we can discuss this tomorrow, also with respect to the target variables!

**Comment by samhennessey** [comment]
@fjebaker Awesome! If we could get that sorted tomorrow that would be great! I also need some clarification on the column names for some of the tables so I know exactly what features I need to input into the models once they're created :)

**Pull request merged**
